### ISSUE TITLE
Integrate with "YouTrack Integration Plugin"

### ISSUE THREAD

**Issue by orybak** [VladRassokhin/intellij-tasks-navigate#1]
If YoutrackOffline (https://github.com/JetBrains/hackathon-YoutrackOffline) plugin is installed, provide option to navigate to issue without leaving IDEA

**Comment by VladRassokhin** [comment]
Whilst YouTrackOffline no longer exist there's [YouTrack Integration Plugin](https://plugins.jetbrains.com/plugin/8215-youtrack-integration-plugin) which is open-sourced and quite widely used.
So I'll investigate how to integrate with it.
