### ISSUE TITLE
Navigation from annotations does not work when defined in default element ('value')

### ISSUE THREAD

**Issue by kool79** [VladRassokhin/intellij-tasks-navigate#5]
In my annotations I use 'value' element which can be omitted. (To be more clear - I use value[]) But navigation does not work for definition:
@TestFor("ABC-111")
And it works properly only when I define element name explicitly:
@TestFor(value = "ABC-111")

**Comment by VladRassokhin** [comment]
Hi,
Sorry, somehow missed notification.
I've released version 0.4.0, where annotation stuff is dropped in favor of using IntelliLang injections. 
Use 'Inject Language' -> 'Task Reference' on any usage of annotation. That would make IntelliLang think that all usages of that annotation should have task reference.
