### ISSUE TITLE
Не работает интеграция с Pivotal Tracker

### ISSUE THREAD

**Issue by arturtr** [VladRassokhin/intellij-tasks-navigate#7]
При запросе задач с сервера возникает ошибка
`Icon cannot be found in '/icons/pivotal/feature.png', aClass='class com.intellij.tasks.LocalTask'`

**Comment by VladRassokhin** [comment]
Looks like it's a problem not in the plugin but in IntelliJ itself: [RUBY-19704](https://youtrack.jetbrains.com/issue/RUBY-19704).
