### ISSUE TITLE
Extract Java-specific part and add explicit (optional) dependency on Java plugin

### ISSUE THREAD

**Issue by chashnikov** [VladRassokhin/intellij-tasks-navigate#9]
The plugin uses some classes which are located in the Java plugin but doesn't declare dependency on it, see [plugin verification results](https://plugins.jetbrains.com/plugin/7241-tasks-navigation/update/21079) for details. This may cause NoClassDefFound errors in IDEs other than IntelliJ IDEA.

**Comment by VladRassokhin** [comment]
Thanks. I've actually removed relevant code a year ago, though haven't released plugin with those changes
